#include "network.hpp"


Network::Network(const std::string & param_folder) :
    // Convolution layers

	/*
    conv1(param_folder + "/conv1_W.npy"),
    res2a_branch1(param_folder + "/res2a_branch1_W.npy"),
    res2a_branch2a(param_folder + "/res2a_branch2a_W.npy"),
    res2a_branch2b(param_folder + "/res2a_branch2b_W.npy"),
    res2a_branch2c(param_folder + "/res2a_branch2c_W.npy"),
    res2b_branch2a(param_folder + "/res2b_branch2a_W.npy"),
    res2b_branch2b(param_folder + "/res2b_branch2b_W.npy"),
    res2b_branch2c(param_folder + "/res2b_branch2c_W.npy"),
    res2c_branch2a(param_folder + "/res2c_branch2a_W.npy"),
    res2c_branch2b(param_folder + "/res2c_branch2b_W.npy"),
    res2c_branch2c(param_folder + "/res2c_branch2c_W.npy"),

    res3a_branch1(param_folder + "/res3a_branch1_W.npy"),
    res3a_branch2a(param_folder + "/res3a_branch2a_W.npy"),
    res3a_branch2b(param_folder + "/res3a_branch2b_W.npy"),
    res3a_branch2c(param_folder + "/res3a_branch2c_W.npy"),
    res3b1_branch2a(param_folder + "/res3b1_branch2a_W.npy"),
    res3b1_branch2b(param_folder + "/res3b1_branch2b_W.npy"),
    res3b1_branch2c(param_folder + "/res3b1_branch2c_W.npy"),
    res3b2_branch2a(param_folder + "/res3b2_branch2a_W.npy"),
    res3b2_branch2b(param_folder + "/res3b2_branch2b_W.npy"),
    res3b2_branch2c(param_folder + "/res3b2_branch2c_W.npy"),
    res3b3_branch2a(param_folder + "/res3b3_branch2a_W.npy"),
    res3b3_branch2b(param_folder + "/res3b3_branch2b_W.npy"),
    res3b3_branch2c(param_folder + "/res3b3_branch2c_W.npy"),
    res3b4_branch2a(param_folder + "/res3b4_branch2a_W.npy"),
    res3b4_branch2b(param_folder + "/res3b4_branch2b_W.npy"),
    res3b4_branch2c(param_folder + "/res3b4_branch2c_W.npy"),
    res3b5_branch2a(param_folder + "/res3b5_branch2a_W.npy"),
    res3b5_branch2b(param_folder + "/res3b5_branch2b_W.npy"),
    res3b5_branch2c(param_folder + "/res3b5_branch2c_W.npy"),
    res3b6_branch2a(param_folder + "/res3b6_branch2a_W.npy"),
    res3b6_branch2b(param_folder + "/res3b6_branch2b_W.npy"),
    res3b6_branch2c(param_folder + "/res3b6_branch2c_W.npy"),
    res3b7_branch2a(param_folder + "/res3b7_branch2a_W.npy"),
    res3b7_branch2b(param_folder + "/res3b7_branch2b_W.npy"),
    res3b7_branch2c(param_folder + "/res3b7_branch2c_W.npy"),

    res4a_branch1(param_folder + "/res4a_branch1_W.npy"),
    res4a_branch2a(param_folder + "/res4a_branch2a_W.npy"),
    res4a_branch2b(param_folder + "/res4a_branch2b_W.npy"),
    res4a_branch2c(param_folder + "/res4a_branch2c_W.npy"),
    res4b1_branch2a(param_folder + "/res4b1_branch2a_W.npy"),
    res4b1_branch2b(param_folder + "/res4b1_branch2b_W.npy"),
    res4b1_branch2c(param_folder + "/res4b1_branch2c_W.npy"),
    res4b2_branch2a(param_folder + "/res4b2_branch2a_W.npy"),
    res4b2_branch2b(param_folder + "/res4b2_branch2b_W.npy"),
    res4b2_branch2c(param_folder + "/res4b2_branch2c_W.npy"),
    res4b3_branch2a(param_folder + "/res4b3_branch2a_W.npy"),
    res4b3_branch2b(param_folder + "/res4b3_branch2b_W.npy"),
    res4b3_branch2c(param_folder + "/res4b3_branch2c_W.npy"),
    res4b4_branch2a(param_folder + "/res4b4_branch2a_W.npy"),
    res4b4_branch2b(param_folder + "/res4b4_branch2b_W.npy"),
    res4b4_branch2c(param_folder + "/res4b4_branch2c_W.npy"),
    res4b5_branch2a(param_folder + "/res4b5_branch2a_W.npy"),
    res4b5_branch2b(param_folder + "/res4b5_branch2b_W.npy"),
    res4b5_branch2c(param_folder + "/res4b5_branch2c_W.npy"),
    res4b6_branch2a(param_folder + "/res4b6_branch2a_W.npy"),
    res4b6_branch2b(param_folder + "/res4b6_branch2b_W.npy"),
    res4b6_branch2c(param_folder + "/res4b6_branch2c_W.npy"),
    res4b7_branch2a(param_folder + "/res4b7_branch2a_W.npy"),
    res4b7_branch2b(param_folder + "/res4b7_branch2b_W.npy"),
    res4b7_branch2c(param_folder + "/res4b7_branch2c_W.npy"),
    res4b8_branch2a(param_folder + "/res4b8_branch2a_W.npy"),
    res4b8_branch2b(param_folder + "/res4b8_branch2b_W.npy"),
    res4b8_branch2c(param_folder + "/res4b8_branch2c_W.npy"),
    res4b9_branch2a(param_folder + "/res4b9_branch2a_W.npy"),
    res4b9_branch2b(param_folder + "/res4b9_branch2b_W.npy"),
    res4b9_branch2c(param_folder + "/res4b9_branch2c_W.npy"),
    res4b10_branch2a(param_folder + "/res4b10_branch2a_W.npy"),
    res4b10_branch2b(param_folder + "/res4b10_branch2b_W.npy"),
    res4b10_branch2c(param_folder + "/res4b10_branch2c_W.npy"),
    res4b11_branch2a(param_folder + "/res4b11_branch2a_W.npy"),
    res4b11_branch2b(param_folder + "/res4b11_branch2b_W.npy"),
    res4b11_branch2c(param_folder + "/res4b11_branch2c_W.npy"),
    res4b12_branch2a(param_folder + "/res4b12_branch2a_W.npy"),
    res4b12_branch2b(param_folder + "/res4b12_branch2b_W.npy"),
    res4b12_branch2c(param_folder + "/res4b12_branch2c_W.npy"),
    res4b13_branch2a(param_folder + "/res4b13_branch2a_W.npy"),
    res4b13_branch2b(param_folder + "/res4b13_branch2b_W.npy"),
    res4b13_branch2c(param_folder + "/res4b13_branch2c_W.npy"),
    res4b14_branch2a(param_folder + "/res4b14_branch2a_W.npy"),
    res4b14_branch2b(param_folder + "/res4b14_branch2b_W.npy"),
    res4b14_branch2c(param_folder + "/res4b14_branch2c_W.npy"),
    res4b15_branch2a(param_folder + "/res4b15_branch2a_W.npy"),
    res4b15_branch2b(param_folder + "/res4b15_branch2b_W.npy"),
    res4b15_branch2c(param_folder + "/res4b15_branch2c_W.npy"),
    res4b16_branch2a(param_folder + "/res4b16_branch2a_W.npy"),
    res4b16_branch2b(param_folder + "/res4b16_branch2b_W.npy"),
    res4b16_branch2c(param_folder + "/res4b16_branch2c_W.npy"),
    res4b17_branch2a(param_folder + "/res4b17_branch2a_W.npy"),
    res4b17_branch2b(param_folder + "/res4b17_branch2b_W.npy"),
    res4b17_branch2c(param_folder + "/res4b17_branch2c_W.npy"),
    res4b18_branch2a(param_folder + "/res4b18_branch2a_W.npy"),
    res4b18_branch2b(param_folder + "/res4b18_branch2b_W.npy"),
    res4b18_branch2c(param_folder + "/res4b18_branch2c_W.npy"),
    res4b19_branch2a(param_folder + "/res4b19_branch2a_W.npy"),
    res4b19_branch2b(param_folder + "/res4b19_branch2b_W.npy"),
    res4b19_branch2c(param_folder + "/res4b19_branch2c_W.npy"),
    res4b20_branch2a(param_folder + "/res4b20_branch2a_W.npy"),
    res4b20_branch2b(param_folder + "/res4b20_branch2b_W.npy"),
    res4b20_branch2c(param_folder + "/res4b20_branch2c_W.npy"),
    res4b21_branch2a(param_folder + "/res4b21_branch2a_W.npy"),
    res4b21_branch2b(param_folder + "/res4b21_branch2b_W.npy"),
    res4b21_branch2c(param_folder + "/res4b21_branch2c_W.npy"),
    res4b22_branch2a(param_folder + "/res4b22_branch2a_W.npy"),
    res4b22_branch2b(param_folder + "/res4b22_branch2b_W.npy"),
    res4b22_branch2c(param_folder + "/res4b22_branch2c_W.npy"),
    res4b23_branch2a(param_folder + "/res4b23_branch2a_W.npy"),
    res4b23_branch2b(param_folder + "/res4b23_branch2b_W.npy"),
    res4b23_branch2c(param_folder + "/res4b23_branch2c_W.npy"),
    res4b24_branch2a(param_folder + "/res4b24_branch2a_W.npy"),
    res4b24_branch2b(param_folder + "/res4b24_branch2b_W.npy"),
    res4b24_branch2c(param_folder + "/res4b24_branch2c_W.npy"),
    res4b25_branch2a(param_folder + "/res4b25_branch2a_W.npy"),
    res4b25_branch2b(param_folder + "/res4b25_branch2b_W.npy"),
    res4b25_branch2c(param_folder + "/res4b25_branch2c_W.npy"),
    res4b26_branch2a(param_folder + "/res4b26_branch2a_W.npy"),
    res4b26_branch2b(param_folder + "/res4b26_branch2b_W.npy"),
    res4b26_branch2c(param_folder + "/res4b26_branch2c_W.npy"),
    res4b27_branch2a(param_folder + "/res4b27_branch2a_W.npy"),
    res4b27_branch2b(param_folder + "/res4b27_branch2b_W.npy"),
    res4b27_branch2c(param_folder + "/res4b27_branch2c_W.npy"),
    res4b28_branch2a(param_folder + "/res4b28_branch2a_W.npy"),
    res4b28_branch2b(param_folder + "/res4b28_branch2b_W.npy"),
    res4b28_branch2c(param_folder + "/res4b28_branch2c_W.npy"),
    res4b29_branch2a(param_folder + "/res4b29_branch2a_W.npy"),
    res4b29_branch2b(param_folder + "/res4b29_branch2b_W.npy"),
    res4b29_branch2c(param_folder + "/res4b29_branch2c_W.npy"),
    res4b30_branch2a(param_folder + "/res4b30_branch2a_W.npy"),
    res4b30_branch2b(param_folder + "/res4b30_branch2b_W.npy"),
    res4b30_branch2c(param_folder + "/res4b30_branch2c_W.npy"),
    res4b31_branch2a(param_folder + "/res4b31_branch2a_W.npy"),
    res4b31_branch2b(param_folder + "/res4b31_branch2b_W.npy"),
    res4b31_branch2c(param_folder + "/res4b31_branch2c_W.npy"),
    res4b32_branch2a(param_folder + "/res4b32_branch2a_W.npy"),
    res4b32_branch2b(param_folder + "/res4b32_branch2b_W.npy"),
    res4b32_branch2c(param_folder + "/res4b32_branch2c_W.npy"),
    res4b33_branch2a(param_folder + "/res4b33_branch2a_W.npy"),
    res4b33_branch2b(param_folder + "/res4b33_branch2b_W.npy"),
    res4b33_branch2c(param_folder + "/res4b33_branch2c_W.npy"),
    res4b34_branch2a(param_folder + "/res4b34_branch2a_W.npy"),
    res4b34_branch2b(param_folder + "/res4b34_branch2b_W.npy"),
    res4b34_branch2c(param_folder + "/res4b34_branch2c_W.npy"),
    res4b35_branch2a(param_folder + "/res4b35_branch2a_W.npy"),
    res4b35_branch2b(param_folder + "/res4b35_branch2b_W.npy"),
    res4b35_branch2c(param_folder + "/res4b35_branch2c_W.npy"),

    res5a_branch1(param_folder + "/res5a_branch1_W.npy"),
    res5a_branch2a(param_folder + "/res5a_branch2a_W.npy"),
    res5a_branch2b(param_folder + "/res5a_branch2b_W.npy"),
    res5a_branch2c(param_folder + "/res5a_branch2c_W.npy"),
    res5b_branch2a(param_folder + "/res5b_branch2a_W.npy"),
    res5b_branch2b(param_folder + "/res5b_branch2b_W.npy"),
    res5b_branch2c(param_folder + "/res5b_branch2c_W.npy"),
    res5c_branch2a(param_folder + "/res5c_branch2a_W.npy"),
    res5c_branch2b(param_folder + "/res5c_branch2b_W.npy"),
    res5c_branch2c(param_folder + "/res5c_branch2c_W.npy"),
	*/

    // Fast convolution layers
    conv1(param_folder + "/conv1_W.npy",
          param_folder + "/decomposition/conv1_W/basis_6/M.npy",
          param_folder + "/decomposition/conv1_W/basis_6/c.npy"),
    res2a_branch1(param_folder + "/res2a_branch1_W.npy",
                  param_folder + "/decomposition/res2a_branch1_W/basis_6/M.npy",
                  param_folder + "/decomposition/res2a_branch1_W/basis_6/c.npy"),
    res2a_branch2a(param_folder + "/res2a_branch2a_W.npy",
                   param_folder + "/decomposition/res2a_branch2a_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2a_branch2a_W/basis_6/c.npy"),
    res2a_branch2b(param_folder + "/res2a_branch2b_W.npy",
                   param_folder + "/decomposition/res2a_branch2b_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2a_branch2b_W/basis_6/c.npy"),
    res2a_branch2c(param_folder + "/res2a_branch2c_W.npy",
                   param_folder + "/decomposition/res2a_branch2c_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2a_branch2c_W/basis_6/c.npy"),
    res2b_branch2a(param_folder + "/res2b_branch2a_W.npy",
                   param_folder + "/decomposition/res2b_branch2a_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2b_branch2a_W/basis_6/c.npy"),
    res2b_branch2b(param_folder + "/res2b_branch2b_W.npy",
                   param_folder + "/decomposition/res2b_branch2b_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2b_branch2b_W/basis_6/c.npy"),
    res2b_branch2c(param_folder + "/res2b_branch2c_W.npy",
                   param_folder + "/decomposition/res2b_branch2c_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2b_branch2c_W/basis_6/c.npy"),
    res2c_branch2a(param_folder + "/res2c_branch2a_W.npy",
                   param_folder + "/decomposition/res2c_branch2a_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2c_branch2a_W/basis_6/c.npy"),
    res2c_branch2b(param_folder + "/res2c_branch2b_W.npy",
                   param_folder + "/decomposition/res2c_branch2b_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2c_branch2b_W/basis_6/c.npy"),
    res2c_branch2c(param_folder + "/res2c_branch2c_W.npy",
                   param_folder + "/decomposition/res2c_branch2c_W/basis_6/M.npy",
                   param_folder + "/decomposition/res2c_branch2c_W/basis_6/c.npy"),

    res3a_branch1(param_folder + "/res3a_branch1_W.npy",
                  param_folder + "/decomposition/res3a_branch1_W/basis_6/M.npy",
                  param_folder + "/decomposition/res3a_branch1_W/basis_6/c.npy"),
    res3a_branch2a(param_folder + "/res3a_branch2a_W.npy",
                   param_folder + "/decomposition/res3a_branch2a_W/basis_6/M.npy",
                   param_folder + "/decomposition/res3a_branch2a_W/basis_6/c.npy"),
    res3a_branch2b(param_folder + "/res3a_branch2b_W.npy",
                   param_folder + "/decomposition/res3a_branch2b_W/basis_6/M.npy",
                   param_folder + "/decomposition/res3a_branch2b_W/basis_6/c.npy"),
    res3a_branch2c(param_folder + "/res3a_branch2c_W.npy",
                   param_folder + "/decomposition/res3a_branch2c_W/basis_6/M.npy",
                   param_folder + "/decomposition/res3a_branch2c_W/basis_6/c.npy"),
    res3b1_branch2a(param_folder + "/res3b1_branch2a_W.npy",
                    param_folder + "/decomposition/res3b1_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b1_branch2a_W/basis_6/c.npy"),
    res3b1_branch2b(param_folder + "/res3b1_branch2b_W.npy",
                    param_folder + "/decomposition/res3b1_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b1_branch2b_W/basis_6/c.npy"),
    res3b1_branch2c(param_folder + "/res3b1_branch2c_W.npy",
                    param_folder + "/decomposition/res3b1_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b1_branch2c_W/basis_6/c.npy"),
    res3b2_branch2a(param_folder + "/res3b2_branch2a_W.npy",
                    param_folder + "/decomposition/res3b2_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b2_branch2a_W/basis_6/c.npy"),
    res3b2_branch2b(param_folder + "/res3b2_branch2b_W.npy",
                    param_folder + "/decomposition/res3b2_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b2_branch2b_W/basis_6/c.npy"),
    res3b2_branch2c(param_folder + "/res3b2_branch2c_W.npy",
                    param_folder + "/decomposition/res3b2_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b2_branch2c_W/basis_6/c.npy"),
    res3b3_branch2a(param_folder + "/res3b3_branch2a_W.npy",
                    param_folder + "/decomposition/res3b3_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b3_branch2a_W/basis_6/c.npy"),
    res3b3_branch2b(param_folder + "/res3b3_branch2b_W.npy",
                    param_folder + "/decomposition/res3b3_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b3_branch2b_W/basis_6/c.npy"),
    res3b3_branch2c(param_folder + "/res3b3_branch2c_W.npy",
                    param_folder + "/decomposition/res3b3_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b3_branch2c_W/basis_6/c.npy"),
    res3b4_branch2a(param_folder + "/res3b4_branch2a_W.npy",
                    param_folder + "/decomposition/res3b4_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b4_branch2a_W/basis_6/c.npy"),
    res3b4_branch2b(param_folder + "/res3b4_branch2b_W.npy",
                    param_folder + "/decomposition/res3b4_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b4_branch2b_W/basis_6/c.npy"),
    res3b4_branch2c(param_folder + "/res3b4_branch2c_W.npy",
                    param_folder + "/decomposition/res3b4_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b4_branch2c_W/basis_6/c.npy"),
    res3b5_branch2a(param_folder + "/res3b5_branch2a_W.npy",
                    param_folder + "/decomposition/res3b5_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b5_branch2a_W/basis_6/c.npy"),
    res3b5_branch2b(param_folder + "/res3b5_branch2b_W.npy",
                    param_folder + "/decomposition/res3b5_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b5_branch2b_W/basis_6/c.npy"),
    res3b5_branch2c(param_folder + "/res3b5_branch2c_W.npy",
                    param_folder + "/decomposition/res3b5_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b5_branch2c_W/basis_6/c.npy"),
    res3b6_branch2a(param_folder + "/res3b6_branch2a_W.npy",
                    param_folder + "/decomposition/res3b6_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b6_branch2a_W/basis_6/c.npy"),
    res3b6_branch2b(param_folder + "/res3b6_branch2b_W.npy",
                    param_folder + "/decomposition/res3b6_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b6_branch2b_W/basis_6/c.npy"),
    res3b6_branch2c(param_folder + "/res3b6_branch2c_W.npy",
                    param_folder + "/decomposition/res3b6_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b6_branch2c_W/basis_6/c.npy"),
    res3b7_branch2a(param_folder + "/res3b7_branch2a_W.npy",
                    param_folder + "/decomposition/res3b7_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b7_branch2a_W/basis_6/c.npy"),
    res3b7_branch2b(param_folder + "/res3b7_branch2b_W.npy",
                    param_folder + "/decomposition/res3b7_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b7_branch2b_W/basis_6/c.npy"),
    res3b7_branch2c(param_folder + "/res3b7_branch2c_W.npy",
                    param_folder + "/decomposition/res3b7_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res3b7_branch2c_W/basis_6/c.npy"),

    res4a_branch1(param_folder + "/res4a_branch1_W.npy",
                  param_folder + "/decomposition/res4a_branch1_W/basis_6/M.npy",
                  param_folder + "/decomposition/res4a_branch1_W/basis_6/c.npy"),
    res4a_branch2a(param_folder + "/res4a_branch2a_W.npy",
                   param_folder + "/decomposition/res4a_branch2a_W/basis_6/M.npy",
                   param_folder + "/decomposition/res4a_branch2a_W/basis_6/c.npy"),
    res4a_branch2b(param_folder + "/res4a_branch2b_W.npy",
                   param_folder + "/decomposition/res4a_branch2b_W/basis_6/M.npy",
                   param_folder + "/decomposition/res4a_branch2b_W/basis_6/c.npy"),
    res4a_branch2c(param_folder + "/res4a_branch2c_W.npy",
                   param_folder + "/decomposition/res4a_branch2c_W/basis_6/M.npy",
                   param_folder + "/decomposition/res4a_branch2c_W/basis_6/c.npy"),
    res4b1_branch2a(param_folder + "/res4b1_branch2a_W.npy",
                    param_folder + "/decomposition/res4b1_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b1_branch2a_W/basis_6/c.npy"),
    res4b1_branch2b(param_folder + "/res4b1_branch2b_W.npy",
                    param_folder + "/decomposition/res4b1_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b1_branch2b_W/basis_6/c.npy"),
    res4b1_branch2c(param_folder + "/res4b1_branch2c_W.npy",
                    param_folder + "/decomposition/res4b1_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b1_branch2c_W/basis_6/c.npy"),
    res4b2_branch2a(param_folder + "/res4b2_branch2a_W.npy",
                    param_folder + "/decomposition/res4b2_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b2_branch2a_W/basis_6/c.npy"),
    res4b2_branch2b(param_folder + "/res4b2_branch2b_W.npy",
                    param_folder + "/decomposition/res4b2_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b2_branch2b_W/basis_6/c.npy"),
    res4b2_branch2c(param_folder + "/res4b2_branch2c_W.npy",
                    param_folder + "/decomposition/res4b2_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b2_branch2c_W/basis_6/c.npy"),
    res4b3_branch2a(param_folder + "/res4b3_branch2a_W.npy",
                    param_folder + "/decomposition/res4b3_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b3_branch2a_W/basis_6/c.npy"),
    res4b3_branch2b(param_folder + "/res4b3_branch2b_W.npy",
                    param_folder + "/decomposition/res4b3_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b3_branch2b_W/basis_6/c.npy"),
    res4b3_branch2c(param_folder + "/res4b3_branch2c_W.npy",
                    param_folder + "/decomposition/res4b3_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b3_branch2c_W/basis_6/c.npy"),
    res4b4_branch2a(param_folder + "/res4b4_branch2a_W.npy",
                    param_folder + "/decomposition/res4b4_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b4_branch2a_W/basis_6/c.npy"),
    res4b4_branch2b(param_folder + "/res4b4_branch2b_W.npy",
                    param_folder + "/decomposition/res4b4_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b4_branch2b_W/basis_6/c.npy"),
    res4b4_branch2c(param_folder + "/res4b4_branch2c_W.npy",
                    param_folder + "/decomposition/res4b4_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b4_branch2c_W/basis_6/c.npy"),
    res4b5_branch2a(param_folder + "/res4b5_branch2a_W.npy",
                    param_folder + "/decomposition/res4b5_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b5_branch2a_W/basis_6/c.npy"),
    res4b5_branch2b(param_folder + "/res4b5_branch2b_W.npy",
                    param_folder + "/decomposition/res4b5_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b5_branch2b_W/basis_6/c.npy"),
    res4b5_branch2c(param_folder + "/res4b5_branch2c_W.npy",
                    param_folder + "/decomposition/res4b5_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b5_branch2c_W/basis_6/c.npy"),
    res4b6_branch2a(param_folder + "/res4b6_branch2a_W.npy",
                    param_folder + "/decomposition/res4b6_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b6_branch2a_W/basis_6/c.npy"),
    res4b6_branch2b(param_folder + "/res4b6_branch2b_W.npy",
                    param_folder + "/decomposition/res4b6_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b6_branch2b_W/basis_6/c.npy"),
    res4b6_branch2c(param_folder + "/res4b6_branch2c_W.npy",
                    param_folder + "/decomposition/res4b6_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b6_branch2c_W/basis_6/c.npy"),
    res4b7_branch2a(param_folder + "/res4b7_branch2a_W.npy",
                    param_folder + "/decomposition/res4b7_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b7_branch2a_W/basis_6/c.npy"),
    res4b7_branch2b(param_folder + "/res4b7_branch2b_W.npy",
                    param_folder + "/decomposition/res4b7_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b7_branch2b_W/basis_6/c.npy"),
    res4b7_branch2c(param_folder + "/res4b7_branch2c_W.npy",
                    param_folder + "/decomposition/res4b7_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b7_branch2c_W/basis_6/c.npy"),
    res4b8_branch2a(param_folder + "/res4b8_branch2a_W.npy",
                    param_folder + "/decomposition/res4b8_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b8_branch2a_W/basis_6/c.npy"),
    res4b8_branch2b(param_folder + "/res4b8_branch2b_W.npy",
                    param_folder + "/decomposition/res4b8_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b8_branch2b_W/basis_6/c.npy"),
    res4b8_branch2c(param_folder + "/res4b8_branch2c_W.npy",
                    param_folder + "/decomposition/res4b8_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b8_branch2c_W/basis_6/c.npy"),
    res4b9_branch2a(param_folder + "/res4b9_branch2a_W.npy",
                    param_folder + "/decomposition/res4b9_branch2a_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b9_branch2a_W/basis_6/c.npy"),
    res4b9_branch2b(param_folder + "/res4b9_branch2b_W.npy",
                    param_folder + "/decomposition/res4b9_branch2b_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b9_branch2b_W/basis_6/c.npy"),
    res4b9_branch2c(param_folder + "/res4b9_branch2c_W.npy",
                    param_folder + "/decomposition/res4b9_branch2c_W/basis_6/M.npy",
                    param_folder + "/decomposition/res4b9_branch2c_W/basis_6/c.npy"),
    res4b10_branch2a(param_folder + "/res4b10_branch2a_W.npy",
                     param_folder + "/decomposition/res4b10_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b10_branch2a_W/basis_6/c.npy"),
    res4b10_branch2b(param_folder + "/res4b10_branch2b_W.npy",
                     param_folder + "/decomposition/res4b10_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b10_branch2b_W/basis_6/c.npy"),
    res4b10_branch2c(param_folder + "/res4b10_branch2c_W.npy",
                     param_folder + "/decomposition/res4b10_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b10_branch2c_W/basis_6/c.npy"),
    res4b11_branch2a(param_folder + "/res4b11_branch2a_W.npy",
                     param_folder + "/decomposition/res4b11_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b11_branch2a_W/basis_6/c.npy"),
    res4b11_branch2b(param_folder + "/res4b11_branch2b_W.npy",
                     param_folder + "/decomposition/res4b11_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b11_branch2b_W/basis_6/c.npy"),
    res4b11_branch2c(param_folder + "/res4b11_branch2c_W.npy",
                     param_folder + "/decomposition/res4b11_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b11_branch2c_W/basis_6/c.npy"),
    res4b12_branch2a(param_folder + "/res4b12_branch2a_W.npy",
                     param_folder + "/decomposition/res4b12_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b12_branch2a_W/basis_6/c.npy"),
    res4b12_branch2b(param_folder + "/res4b12_branch2b_W.npy",
                     param_folder + "/decomposition/res4b12_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b12_branch2b_W/basis_6/c.npy"),
    res4b12_branch2c(param_folder + "/res4b12_branch2c_W.npy",
                     param_folder + "/decomposition/res4b12_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b12_branch2c_W/basis_6/c.npy"),
    res4b13_branch2a(param_folder + "/res4b13_branch2a_W.npy",
                     param_folder + "/decomposition/res4b13_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b13_branch2a_W/basis_6/c.npy"),
    res4b13_branch2b(param_folder + "/res4b13_branch2b_W.npy",
                     param_folder + "/decomposition/res4b13_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b13_branch2b_W/basis_6/c.npy"),
    res4b13_branch2c(param_folder + "/res4b13_branch2c_W.npy",
                     param_folder + "/decomposition/res4b13_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b13_branch2c_W/basis_6/c.npy"),
    res4b14_branch2a(param_folder + "/res4b14_branch2a_W.npy",
                     param_folder + "/decomposition/res4b14_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b14_branch2a_W/basis_6/c.npy"),
    res4b14_branch2b(param_folder + "/res4b14_branch2b_W.npy",
                     param_folder + "/decomposition/res4b14_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b14_branch2b_W/basis_6/c.npy"),
    res4b14_branch2c(param_folder + "/res4b14_branch2c_W.npy",
                     param_folder + "/decomposition/res4b14_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b14_branch2c_W/basis_6/c.npy"),
    res4b15_branch2a(param_folder + "/res4b15_branch2a_W.npy",
                     param_folder + "/decomposition/res4b15_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b15_branch2a_W/basis_6/c.npy"),
    res4b15_branch2b(param_folder + "/res4b15_branch2b_W.npy",
                     param_folder + "/decomposition/res4b15_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b15_branch2b_W/basis_6/c.npy"),
    res4b15_branch2c(param_folder + "/res4b15_branch2c_W.npy",
                     param_folder + "/decomposition/res4b15_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b15_branch2c_W/basis_6/c.npy"),
    res4b16_branch2a(param_folder + "/res4b16_branch2a_W.npy",
                     param_folder + "/decomposition/res4b16_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b16_branch2a_W/basis_6/c.npy"),
    res4b16_branch2b(param_folder + "/res4b16_branch2b_W.npy",
                     param_folder + "/decomposition/res4b16_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b16_branch2b_W/basis_6/c.npy"),
    res4b16_branch2c(param_folder + "/res4b16_branch2c_W.npy",
                     param_folder + "/decomposition/res4b16_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b16_branch2c_W/basis_6/c.npy"),
    res4b17_branch2a(param_folder + "/res4b17_branch2a_W.npy",
                     param_folder + "/decomposition/res4b17_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b17_branch2a_W/basis_6/c.npy"),
    res4b17_branch2b(param_folder + "/res4b17_branch2b_W.npy",
                     param_folder + "/decomposition/res4b17_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b17_branch2b_W/basis_6/c.npy"),
    res4b17_branch2c(param_folder + "/res4b17_branch2c_W.npy",
                     param_folder + "/decomposition/res4b17_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b17_branch2c_W/basis_6/c.npy"),
    res4b18_branch2a(param_folder + "/res4b18_branch2a_W.npy",
                     param_folder + "/decomposition/res4b18_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b18_branch2a_W/basis_6/c.npy"),
    res4b18_branch2b(param_folder + "/res4b18_branch2b_W.npy",
                     param_folder + "/decomposition/res4b18_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b18_branch2b_W/basis_6/c.npy"),
    res4b18_branch2c(param_folder + "/res4b18_branch2c_W.npy",
                     param_folder + "/decomposition/res4b18_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b18_branch2c_W/basis_6/c.npy"),
    res4b19_branch2a(param_folder + "/res4b19_branch2a_W.npy",
                     param_folder + "/decomposition/res4b19_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b19_branch2a_W/basis_6/c.npy"),
    res4b19_branch2b(param_folder + "/res4b19_branch2b_W.npy",
                     param_folder + "/decomposition/res4b19_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b19_branch2b_W/basis_6/c.npy"),
    res4b19_branch2c(param_folder + "/res4b19_branch2c_W.npy",
                     param_folder + "/decomposition/res4b19_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b19_branch2c_W/basis_6/c.npy"),
    res4b20_branch2a(param_folder + "/res4b20_branch2a_W.npy",
                     param_folder + "/decomposition/res4b20_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b20_branch2a_W/basis_6/c.npy"),
    res4b20_branch2b(param_folder + "/res4b20_branch2b_W.npy",
                     param_folder + "/decomposition/res4b20_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b20_branch2b_W/basis_6/c.npy"),
    res4b20_branch2c(param_folder + "/res4b20_branch2c_W.npy",
                     param_folder + "/decomposition/res4b20_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b20_branch2c_W/basis_6/c.npy"),
    res4b21_branch2a(param_folder + "/res4b21_branch2a_W.npy",
                     param_folder + "/decomposition/res4b21_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b21_branch2a_W/basis_6/c.npy"),
    res4b21_branch2b(param_folder + "/res4b21_branch2b_W.npy",
                     param_folder + "/decomposition/res4b21_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b21_branch2b_W/basis_6/c.npy"),
    res4b21_branch2c(param_folder + "/res4b21_branch2c_W.npy",
                     param_folder + "/decomposition/res4b21_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b21_branch2c_W/basis_6/c.npy"),
    res4b22_branch2a(param_folder + "/res4b22_branch2a_W.npy",
                     param_folder + "/decomposition/res4b22_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b22_branch2a_W/basis_6/c.npy"),
    res4b22_branch2b(param_folder + "/res4b22_branch2b_W.npy",
                     param_folder + "/decomposition/res4b22_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b22_branch2b_W/basis_6/c.npy"),
    res4b22_branch2c(param_folder + "/res4b22_branch2c_W.npy",
                     param_folder + "/decomposition/res4b22_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b22_branch2c_W/basis_6/c.npy"),
    res4b23_branch2a(param_folder + "/res4b23_branch2a_W.npy",
                     param_folder + "/decomposition/res4b23_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b23_branch2a_W/basis_6/c.npy"),
    res4b23_branch2b(param_folder + "/res4b23_branch2b_W.npy",
                     param_folder + "/decomposition/res4b23_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b23_branch2b_W/basis_6/c.npy"),
    res4b23_branch2c(param_folder + "/res4b23_branch2c_W.npy",
                     param_folder + "/decomposition/res4b23_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b23_branch2c_W/basis_6/c.npy"),
    res4b24_branch2a(param_folder + "/res4b24_branch2a_W.npy",
                     param_folder + "/decomposition/res4b24_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b24_branch2a_W/basis_6/c.npy"),
    res4b24_branch2b(param_folder + "/res4b24_branch2b_W.npy",
                     param_folder + "/decomposition/res4b24_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b24_branch2b_W/basis_6/c.npy"),
    res4b24_branch2c(param_folder + "/res4b24_branch2c_W.npy",
                     param_folder + "/decomposition/res4b24_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b24_branch2c_W/basis_6/c.npy"),
    res4b25_branch2a(param_folder + "/res4b25_branch2a_W.npy",
                     param_folder + "/decomposition/res4b25_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b25_branch2a_W/basis_6/c.npy"),
    res4b25_branch2b(param_folder + "/res4b25_branch2b_W.npy",
                     param_folder + "/decomposition/res4b25_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b25_branch2b_W/basis_6/c.npy"),
    res4b25_branch2c(param_folder + "/res4b25_branch2c_W.npy",
                     param_folder + "/decomposition/res4b25_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b25_branch2c_W/basis_6/c.npy"),
    res4b26_branch2a(param_folder + "/res4b26_branch2a_W.npy",
                     param_folder + "/decomposition/res4b26_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b26_branch2a_W/basis_6/c.npy"),
    res4b26_branch2b(param_folder + "/res4b26_branch2b_W.npy",
                     param_folder + "/decomposition/res4b26_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b26_branch2b_W/basis_6/c.npy"),
    res4b26_branch2c(param_folder + "/res4b26_branch2c_W.npy",
                     param_folder + "/decomposition/res4b26_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b26_branch2c_W/basis_6/c.npy"),
    res4b27_branch2a(param_folder + "/res4b27_branch2a_W.npy",
                     param_folder + "/decomposition/res4b27_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b27_branch2a_W/basis_6/c.npy"),
    res4b27_branch2b(param_folder + "/res4b27_branch2b_W.npy",
                     param_folder + "/decomposition/res4b27_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b27_branch2b_W/basis_6/c.npy"),
    res4b27_branch2c(param_folder + "/res4b27_branch2c_W.npy",
                     param_folder + "/decomposition/res4b27_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b27_branch2c_W/basis_6/c.npy"),
    res4b28_branch2a(param_folder + "/res4b28_branch2a_W.npy",
                     param_folder + "/decomposition/res4b28_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b28_branch2a_W/basis_6/c.npy"),
    res4b28_branch2b(param_folder + "/res4b28_branch2b_W.npy",
                     param_folder + "/decomposition/res4b28_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b28_branch2b_W/basis_6/c.npy"),
    res4b28_branch2c(param_folder + "/res4b28_branch2c_W.npy",
                     param_folder + "/decomposition/res4b28_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b28_branch2c_W/basis_6/c.npy"),
    res4b29_branch2a(param_folder + "/res4b29_branch2a_W.npy",
                     param_folder + "/decomposition/res4b29_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b29_branch2a_W/basis_6/c.npy"),
    res4b29_branch2b(param_folder + "/res4b29_branch2b_W.npy",
                     param_folder + "/decomposition/res4b29_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b29_branch2b_W/basis_6/c.npy"),
    res4b29_branch2c(param_folder + "/res4b29_branch2c_W.npy",
                     param_folder + "/decomposition/res4b29_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b29_branch2c_W/basis_6/c.npy"),
    res4b30_branch2a(param_folder + "/res4b30_branch2a_W.npy",
                     param_folder + "/decomposition/res4b30_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b30_branch2a_W/basis_6/c.npy"),
    res4b30_branch2b(param_folder + "/res4b30_branch2b_W.npy",
                     param_folder + "/decomposition/res4b30_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b30_branch2b_W/basis_6/c.npy"),
    res4b30_branch2c(param_folder + "/res4b30_branch2c_W.npy",
                     param_folder + "/decomposition/res4b30_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b30_branch2c_W/basis_6/c.npy"),
    res4b31_branch2a(param_folder + "/res4b31_branch2a_W.npy",
                     param_folder + "/decomposition/res4b31_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b31_branch2a_W/basis_6/c.npy"),
    res4b31_branch2b(param_folder + "/res4b31_branch2b_W.npy",
                     param_folder + "/decomposition/res4b31_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b31_branch2b_W/basis_6/c.npy"),
    res4b31_branch2c(param_folder + "/res4b31_branch2c_W.npy",
                     param_folder + "/decomposition/res4b31_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b31_branch2c_W/basis_6/c.npy"),
    res4b32_branch2a(param_folder + "/res4b32_branch2a_W.npy",
                     param_folder + "/decomposition/res4b32_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b32_branch2a_W/basis_6/c.npy"),
    res4b32_branch2b(param_folder + "/res4b32_branch2b_W.npy",
                     param_folder + "/decomposition/res4b32_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b32_branch2b_W/basis_6/c.npy"),
    res4b32_branch2c(param_folder + "/res4b32_branch2c_W.npy",
                     param_folder + "/decomposition/res4b32_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b32_branch2c_W/basis_6/c.npy"),
    res4b33_branch2a(param_folder + "/res4b33_branch2a_W.npy",
                     param_folder + "/decomposition/res4b33_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b33_branch2a_W/basis_6/c.npy"),
    res4b33_branch2b(param_folder + "/res4b33_branch2b_W.npy",
                     param_folder + "/decomposition/res4b33_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b33_branch2b_W/basis_6/c.npy"),
    res4b33_branch2c(param_folder + "/res4b33_branch2c_W.npy",
                     param_folder + "/decomposition/res4b33_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b33_branch2c_W/basis_6/c.npy"),
    res4b34_branch2a(param_folder + "/res4b34_branch2a_W.npy",
                     param_folder + "/decomposition/res4b34_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b34_branch2a_W/basis_6/c.npy"),
    res4b34_branch2b(param_folder + "/res4b34_branch2b_W.npy",
                     param_folder + "/decomposition/res4b34_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b34_branch2b_W/basis_6/c.npy"),
    res4b34_branch2c(param_folder + "/res4b34_branch2c_W.npy",
                     param_folder + "/decomposition/res4b34_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b34_branch2c_W/basis_6/c.npy"),
    res4b35_branch2a(param_folder + "/res4b35_branch2a_W.npy",
                     param_folder + "/decomposition/res4b35_branch2a_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b35_branch2a_W/basis_6/c.npy"),
    res4b35_branch2b(param_folder + "/res4b35_branch2b_W.npy",
                     param_folder + "/decomposition/res4b35_branch2b_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b35_branch2b_W/basis_6/c.npy"),
    res4b35_branch2c(param_folder + "/res4b35_branch2c_W.npy",
                     param_folder + "/decomposition/res4b35_branch2c_W/basis_6/M.npy",
                     param_folder + "/decomposition/res4b35_branch2c_W/basis_6/c.npy"),

    res5a_branch1(param_folder + "/res5a_branch1_W.npy",
                  param_folder + "/decomposition/res5a_branch1_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5a_branch1_W/basis_6/c.npy"),
    res5a_branch2a(param_folder + "/res5a_branch2a_W.npy",
                  param_folder + "/decomposition/res5a_branch2a_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5a_branch2a_W/basis_6/c.npy"),
    res5a_branch2b(param_folder + "/res5a_branch2b_W.npy",
                  param_folder + "/decomposition/res5a_branch2b_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5a_branch2b_W/basis_6/c.npy"),
    res5a_branch2c(param_folder + "/res5a_branch2c_W.npy",
                  param_folder + "/decomposition/res5a_branch2c_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5a_branch2c_W/basis_6/c.npy"),
    res5b_branch2a(param_folder + "/res5b_branch2a_W.npy",
                  param_folder + "/decomposition/res5b_branch2a_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5b_branch2a_W/basis_6/c.npy"),
    res5b_branch2b(param_folder + "/res5b_branch2b_W.npy",
                  param_folder + "/decomposition/res5b_branch2b_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5b_branch2b_W/basis_6/c.npy"),
    res5b_branch2c(param_folder + "/res5b_branch2c_W.npy",
                  param_folder + "/decomposition/res5b_branch2c_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5b_branch2c_W/basis_6/c.npy"),
    res5c_branch2a(param_folder + "/res5c_branch2a_W.npy",
                  param_folder + "/decomposition/res5c_branch2a_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5c_branch2a_W/basis_6/c.npy"),
    res5c_branch2b(param_folder + "/res5c_branch2b_W.npy",
                  param_folder + "/decomposition/res5c_branch2b_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5c_branch2b_W/basis_6/c.npy"),
    res5c_branch2c(param_folder + "/res5c_branch2c_W.npy",
                  param_folder + "/decomposition/res5c_branch2c_W/basis_6/M.npy",
                  param_folder + "/decomposition/res5c_branch2c_W/basis_6/c.npy"),

    // Batch normalization layers
    bn_conv1(param_folder + "/bn_conv1_mean.npy", param_folder + "/bn_conv1_var.npy", param_folder + "/scale_conv1_W.npy", param_folder + "/scale_conv1_b.npy"),

    bn2a_branch1(param_folder + "/bn2a_branch1_mean.npy", param_folder + "/bn2a_branch1_var.npy", param_folder + "/scale2a_branch1_W.npy", param_folder + "/scale2a_branch1_b.npy"),
    bn2a_branch2a(param_folder + "/bn2a_branch2a_mean.npy", param_folder + "/bn2a_branch2a_var.npy", param_folder + "/scale2a_branch2a_W.npy", param_folder + "/scale2a_branch2a_b.npy"),
    bn2a_branch2b(param_folder + "/bn2a_branch2b_mean.npy", param_folder + "/bn2a_branch2b_var.npy", param_folder + "/scale2a_branch2b_W.npy", param_folder + "/scale2a_branch2b_b.npy"),
    bn2a_branch2c(param_folder + "/bn2a_branch2c_mean.npy", param_folder + "/bn2a_branch2c_var.npy", param_folder + "/scale2a_branch2c_W.npy", param_folder + "/scale2a_branch2c_b.npy"),
    bn2b_branch2a(param_folder + "/bn2b_branch2a_mean.npy", param_folder + "/bn2b_branch2a_var.npy", param_folder + "/scale2b_branch2a_W.npy", param_folder + "/scale2b_branch2a_b.npy"),
    bn2b_branch2b(param_folder + "/bn2b_branch2b_mean.npy", param_folder + "/bn2b_branch2b_var.npy", param_folder + "/scale2b_branch2b_W.npy", param_folder + "/scale2b_branch2b_b.npy"),
    bn2b_branch2c(param_folder + "/bn2b_branch2c_mean.npy", param_folder + "/bn2b_branch2c_var.npy", param_folder + "/scale2b_branch2c_W.npy", param_folder + "/scale2b_branch2c_b.npy"),
    bn2c_branch2a(param_folder + "/bn2c_branch2a_mean.npy", param_folder + "/bn2c_branch2a_var.npy", param_folder + "/scale2c_branch2a_W.npy", param_folder + "/scale2c_branch2a_b.npy"),
    bn2c_branch2b(param_folder + "/bn2c_branch2b_mean.npy", param_folder + "/bn2c_branch2b_var.npy", param_folder + "/scale2c_branch2b_W.npy", param_folder + "/scale2c_branch2b_b.npy"),
    bn2c_branch2c(param_folder + "/bn2c_branch2c_mean.npy", param_folder + "/bn2c_branch2c_var.npy", param_folder + "/scale2c_branch2c_W.npy", param_folder + "/scale2c_branch2c_b.npy"),

    bn3a_branch1(param_folder + "/bn3a_branch1_mean.npy", param_folder + "/bn3a_branch1_var.npy", param_folder + "/scale3a_branch1_W.npy", param_folder + "/scale3a_branch1_b.npy"),
    bn3a_branch2a(param_folder + "/bn3a_branch2a_mean.npy", param_folder + "/bn3a_branch2a_var.npy", param_folder + "/scale3a_branch2a_W.npy", param_folder + "/scale3a_branch2a_b.npy"),
    bn3a_branch2b(param_folder + "/bn3a_branch2b_mean.npy", param_folder + "/bn3a_branch2b_var.npy", param_folder + "/scale3a_branch2b_W.npy", param_folder + "/scale3a_branch2b_b.npy"),
    bn3a_branch2c(param_folder + "/bn3a_branch2c_mean.npy", param_folder + "/bn3a_branch2c_var.npy", param_folder + "/scale3a_branch2c_W.npy", param_folder + "/scale3a_branch2c_b.npy"),
    bn3b1_branch2a(param_folder + "/bn3b1_branch2a_mean.npy", param_folder + "/bn3b1_branch2a_var.npy", param_folder + "/scale3b1_branch2a_W.npy", param_folder + "/scale3b1_branch2a_b.npy"),
    bn3b1_branch2b(param_folder + "/bn3b1_branch2b_mean.npy", param_folder + "/bn3b1_branch2b_var.npy", param_folder + "/scale3b1_branch2b_W.npy", param_folder + "/scale3b1_branch2b_b.npy"),
    bn3b1_branch2c(param_folder + "/bn3b1_branch2c_mean.npy", param_folder + "/bn3b1_branch2c_var.npy", param_folder + "/scale3b1_branch2c_W.npy", param_folder + "/scale3b1_branch2c_b.npy"),
    bn3b2_branch2a(param_folder + "/bn3b2_branch2a_mean.npy", param_folder + "/bn3b2_branch2a_var.npy", param_folder + "/scale3b2_branch2a_W.npy", param_folder + "/scale3b2_branch2a_b.npy"),
    bn3b2_branch2b(param_folder + "/bn3b2_branch2b_mean.npy", param_folder + "/bn3b2_branch2b_var.npy", param_folder + "/scale3b2_branch2b_W.npy", param_folder + "/scale3b2_branch2b_b.npy"),
    bn3b2_branch2c(param_folder + "/bn3b2_branch2c_mean.npy", param_folder + "/bn3b2_branch2c_var.npy", param_folder + "/scale3b2_branch2c_W.npy", param_folder + "/scale3b2_branch2c_b.npy"),
    bn3b3_branch2a(param_folder + "/bn3b3_branch2a_mean.npy", param_folder + "/bn3b3_branch2a_var.npy", param_folder + "/scale3b3_branch2a_W.npy", param_folder + "/scale3b3_branch2a_b.npy"),
    bn3b3_branch2b(param_folder + "/bn3b3_branch2b_mean.npy", param_folder + "/bn3b3_branch2b_var.npy", param_folder + "/scale3b3_branch2b_W.npy", param_folder + "/scale3b3_branch2b_b.npy"),
    bn3b3_branch2c(param_folder + "/bn3b3_branch2c_mean.npy", param_folder + "/bn3b3_branch2c_var.npy", param_folder + "/scale3b3_branch2c_W.npy", param_folder + "/scale3b3_branch2c_b.npy"),
    bn3b4_branch2a(param_folder + "/bn3b4_branch2a_mean.npy", param_folder + "/bn3b4_branch2a_var.npy", param_folder + "/scale3b4_branch2a_W.npy", param_folder + "/scale3b4_branch2a_b.npy"),
    bn3b4_branch2b(param_folder + "/bn3b4_branch2b_mean.npy", param_folder + "/bn3b4_branch2b_var.npy", param_folder + "/scale3b4_branch2b_W.npy", param_folder + "/scale3b4_branch2b_b.npy"),
    bn3b4_branch2c(param_folder + "/bn3b4_branch2c_mean.npy", param_folder + "/bn3b4_branch2c_var.npy", param_folder + "/scale3b4_branch2c_W.npy", param_folder + "/scale3b4_branch2c_b.npy"),
    bn3b5_branch2a(param_folder + "/bn3b5_branch2a_mean.npy", param_folder + "/bn3b5_branch2a_var.npy", param_folder + "/scale3b5_branch2a_W.npy", param_folder + "/scale3b5_branch2a_b.npy"),
    bn3b5_branch2b(param_folder + "/bn3b5_branch2b_mean.npy", param_folder + "/bn3b5_branch2b_var.npy", param_folder + "/scale3b5_branch2b_W.npy", param_folder + "/scale3b5_branch2b_b.npy"),
    bn3b5_branch2c(param_folder + "/bn3b5_branch2c_mean.npy", param_folder + "/bn3b5_branch2c_var.npy", param_folder + "/scale3b5_branch2c_W.npy", param_folder + "/scale3b5_branch2c_b.npy"),
    bn3b6_branch2a(param_folder + "/bn3b6_branch2a_mean.npy", param_folder + "/bn3b6_branch2a_var.npy", param_folder + "/scale3b6_branch2a_W.npy", param_folder + "/scale3b6_branch2a_b.npy"),
    bn3b6_branch2b(param_folder + "/bn3b6_branch2b_mean.npy", param_folder + "/bn3b6_branch2b_var.npy", param_folder + "/scale3b6_branch2b_W.npy", param_folder + "/scale3b6_branch2b_b.npy"),
    bn3b6_branch2c(param_folder + "/bn3b6_branch2c_mean.npy", param_folder + "/bn3b6_branch2c_var.npy", param_folder + "/scale3b6_branch2c_W.npy", param_folder + "/scale3b6_branch2c_b.npy"),
    bn3b7_branch2a(param_folder + "/bn3b7_branch2a_mean.npy", param_folder + "/bn3b7_branch2a_var.npy", param_folder + "/scale3b7_branch2a_W.npy", param_folder + "/scale3b7_branch2a_b.npy"),
    bn3b7_branch2b(param_folder + "/bn3b7_branch2b_mean.npy", param_folder + "/bn3b7_branch2b_var.npy", param_folder + "/scale3b7_branch2b_W.npy", param_folder + "/scale3b7_branch2b_b.npy"),
    bn3b7_branch2c(param_folder + "/bn3b7_branch2c_mean.npy", param_folder + "/bn3b7_branch2c_var.npy", param_folder + "/scale3b7_branch2c_W.npy", param_folder + "/scale3b7_branch2c_b.npy"),

    bn4a_branch1(param_folder + "/bn4a_branch1_mean.npy", param_folder + "/bn4a_branch1_var.npy", param_folder + "/scale4a_branch1_W.npy", param_folder + "/scale4a_branch1_b.npy"),
    bn4a_branch2a(param_folder + "/bn4a_branch2a_mean.npy", param_folder + "/bn4a_branch2a_var.npy", param_folder + "/scale4a_branch2a_W.npy", param_folder + "/scale4a_branch2a_b.npy"),
    bn4a_branch2b(param_folder + "/bn4a_branch2b_mean.npy", param_folder + "/bn4a_branch2b_var.npy", param_folder + "/scale4a_branch2b_W.npy", param_folder + "/scale4a_branch2b_b.npy"),
    bn4a_branch2c(param_folder + "/bn4a_branch2c_mean.npy", param_folder + "/bn4a_branch2c_var.npy", param_folder + "/scale4a_branch2c_W.npy", param_folder + "/scale4a_branch2c_b.npy"),
    bn4b1_branch2a(param_folder + "/bn4b1_branch2a_mean.npy", param_folder + "/bn4b1_branch2a_var.npy", param_folder + "/scale4b1_branch2a_W.npy", param_folder + "/scale4b1_branch2a_b.npy"),
    bn4b1_branch2b(param_folder + "/bn4b1_branch2b_mean.npy", param_folder + "/bn4b1_branch2b_var.npy", param_folder + "/scale4b1_branch2b_W.npy", param_folder + "/scale4b1_branch2b_b.npy"),
    bn4b1_branch2c(param_folder + "/bn4b1_branch2c_mean.npy", param_folder + "/bn4b1_branch2c_var.npy", param_folder + "/scale4b1_branch2c_W.npy", param_folder + "/scale4b1_branch2c_b.npy"),
    bn4b2_branch2a(param_folder + "/bn4b2_branch2a_mean.npy", param_folder + "/bn4b2_branch2a_var.npy", param_folder + "/scale4b2_branch2a_W.npy", param_folder + "/scale4b2_branch2a_b.npy"),
    bn4b2_branch2b(param_folder + "/bn4b2_branch2b_mean.npy", param_folder + "/bn4b2_branch2b_var.npy", param_folder + "/scale4b2_branch2b_W.npy", param_folder + "/scale4b2_branch2b_b.npy"),
    bn4b2_branch2c(param_folder + "/bn4b2_branch2c_mean.npy", param_folder + "/bn4b2_branch2c_var.npy", param_folder + "/scale4b2_branch2c_W.npy", param_folder + "/scale4b2_branch2c_b.npy"),
    bn4b3_branch2a(param_folder + "/bn4b3_branch2a_mean.npy", param_folder + "/bn4b3_branch2a_var.npy", param_folder + "/scale4b3_branch2a_W.npy", param_folder + "/scale4b3_branch2a_b.npy"),
    bn4b3_branch2b(param_folder + "/bn4b3_branch2b_mean.npy", param_folder + "/bn4b3_branch2b_var.npy", param_folder + "/scale4b3_branch2b_W.npy", param_folder + "/scale4b3_branch2b_b.npy"),
    bn4b3_branch2c(param_folder + "/bn4b3_branch2c_mean.npy", param_folder + "/bn4b3_branch2c_var.npy", param_folder + "/scale4b3_branch2c_W.npy", param_folder + "/scale4b3_branch2c_b.npy"),
    bn4b4_branch2a(param_folder + "/bn4b4_branch2a_mean.npy", param_folder + "/bn4b4_branch2a_var.npy", param_folder + "/scale4b4_branch2a_W.npy", param_folder + "/scale4b4_branch2a_b.npy"),
    bn4b4_branch2b(param_folder + "/bn4b4_branch2b_mean.npy", param_folder + "/bn4b4_branch2b_var.npy", param_folder + "/scale4b4_branch2b_W.npy", param_folder + "/scale4b4_branch2b_b.npy"),
    bn4b4_branch2c(param_folder + "/bn4b4_branch2c_mean.npy", param_folder + "/bn4b4_branch2c_var.npy", param_folder + "/scale4b4_branch2c_W.npy", param_folder + "/scale4b4_branch2c_b.npy"),
    bn4b5_branch2a(param_folder + "/bn4b5_branch2a_mean.npy", param_folder + "/bn4b5_branch2a_var.npy", param_folder + "/scale4b5_branch2a_W.npy", param_folder + "/scale4b5_branch2a_b.npy"),
    bn4b5_branch2b(param_folder + "/bn4b5_branch2b_mean.npy", param_folder + "/bn4b5_branch2b_var.npy", param_folder + "/scale4b5_branch2b_W.npy", param_folder + "/scale4b5_branch2b_b.npy"),
    bn4b5_branch2c(param_folder + "/bn4b5_branch2c_mean.npy", param_folder + "/bn4b5_branch2c_var.npy", param_folder + "/scale4b5_branch2c_W.npy", param_folder + "/scale4b5_branch2c_b.npy"),
    bn4b6_branch2a(param_folder + "/bn4b6_branch2a_mean.npy", param_folder + "/bn4b6_branch2a_var.npy", param_folder + "/scale4b6_branch2a_W.npy", param_folder + "/scale4b6_branch2a_b.npy"),
    bn4b6_branch2b(param_folder + "/bn4b6_branch2b_mean.npy", param_folder + "/bn4b6_branch2b_var.npy", param_folder + "/scale4b6_branch2b_W.npy", param_folder + "/scale4b6_branch2b_b.npy"),
    bn4b6_branch2c(param_folder + "/bn4b6_branch2c_mean.npy", param_folder + "/bn4b6_branch2c_var.npy", param_folder + "/scale4b6_branch2c_W.npy", param_folder + "/scale4b6_branch2c_b.npy"),
    bn4b7_branch2a(param_folder + "/bn4b7_branch2a_mean.npy", param_folder + "/bn4b7_branch2a_var.npy", param_folder + "/scale4b7_branch2a_W.npy", param_folder + "/scale4b7_branch2a_b.npy"),
    bn4b7_branch2b(param_folder + "/bn4b7_branch2b_mean.npy", param_folder + "/bn4b7_branch2b_var.npy", param_folder + "/scale4b7_branch2b_W.npy", param_folder + "/scale4b7_branch2b_b.npy"),
    bn4b7_branch2c(param_folder + "/bn4b7_branch2c_mean.npy", param_folder + "/bn4b7_branch2c_var.npy", param_folder + "/scale4b7_branch2c_W.npy", param_folder + "/scale4b7_branch2c_b.npy"),
    bn4b8_branch2a(param_folder + "/bn4b8_branch2a_mean.npy", param_folder + "/bn4b8_branch2a_var.npy", param_folder + "/scale4b8_branch2a_W.npy", param_folder + "/scale4b8_branch2a_b.npy"),
    bn4b8_branch2b(param_folder + "/bn4b8_branch2b_mean.npy", param_folder + "/bn4b8_branch2b_var.npy", param_folder + "/scale4b8_branch2b_W.npy", param_folder + "/scale4b8_branch2b_b.npy"),
    bn4b8_branch2c(param_folder + "/bn4b8_branch2c_mean.npy", param_folder + "/bn4b8_branch2c_var.npy", param_folder + "/scale4b8_branch2c_W.npy", param_folder + "/scale4b8_branch2c_b.npy"),
    bn4b9_branch2a(param_folder + "/bn4b9_branch2a_mean.npy", param_folder + "/bn4b9_branch2a_var.npy", param_folder + "/scale4b9_branch2a_W.npy", param_folder + "/scale4b9_branch2a_b.npy"),
    bn4b9_branch2b(param_folder + "/bn4b9_branch2b_mean.npy", param_folder + "/bn4b9_branch2b_var.npy", param_folder + "/scale4b9_branch2b_W.npy", param_folder + "/scale4b9_branch2b_b.npy"),
    bn4b9_branch2c(param_folder + "/bn4b9_branch2c_mean.npy", param_folder + "/bn4b9_branch2c_var.npy", param_folder + "/scale4b9_branch2c_W.npy", param_folder + "/scale4b9_branch2c_b.npy"),
    bn4b10_branch2a(param_folder + "/bn4b10_branch2a_mean.npy", param_folder + "/bn4b10_branch2a_var.npy", param_folder + "/scale4b10_branch2a_W.npy", param_folder + "/scale4b10_branch2a_b.npy"),
    bn4b10_branch2b(param_folder + "/bn4b10_branch2b_mean.npy", param_folder + "/bn4b10_branch2b_var.npy", param_folder + "/scale4b10_branch2b_W.npy", param_folder + "/scale4b10_branch2b_b.npy"),
    bn4b10_branch2c(param_folder + "/bn4b10_branch2c_mean.npy", param_folder + "/bn4b10_branch2c_var.npy", param_folder + "/scale4b10_branch2c_W.npy", param_folder + "/scale4b10_branch2c_b.npy"),
    bn4b11_branch2a(param_folder + "/bn4b11_branch2a_mean.npy", param_folder + "/bn4b11_branch2a_var.npy", param_folder + "/scale4b11_branch2a_W.npy", param_folder + "/scale4b11_branch2a_b.npy"),
    bn4b11_branch2b(param_folder + "/bn4b11_branch2b_mean.npy", param_folder + "/bn4b11_branch2b_var.npy", param_folder + "/scale4b11_branch2b_W.npy", param_folder + "/scale4b11_branch2b_b.npy"),
    bn4b11_branch2c(param_folder + "/bn4b11_branch2c_mean.npy", param_folder + "/bn4b11_branch2c_var.npy", param_folder + "/scale4b11_branch2c_W.npy", param_folder + "/scale4b11_branch2c_b.npy"),
    bn4b12_branch2a(param_folder + "/bn4b12_branch2a_mean.npy", param_folder + "/bn4b12_branch2a_var.npy", param_folder + "/scale4b12_branch2a_W.npy", param_folder + "/scale4b12_branch2a_b.npy"),
    bn4b12_branch2b(param_folder + "/bn4b12_branch2b_mean.npy", param_folder + "/bn4b12_branch2b_var.npy", param_folder + "/scale4b12_branch2b_W.npy", param_folder + "/scale4b12_branch2b_b.npy"),
    bn4b12_branch2c(param_folder + "/bn4b12_branch2c_mean.npy", param_folder + "/bn4b12_branch2c_var.npy", param_folder + "/scale4b12_branch2c_W.npy", param_folder + "/scale4b12_branch2c_b.npy"),
    bn4b13_branch2a(param_folder + "/bn4b13_branch2a_mean.npy", param_folder + "/bn4b13_branch2a_var.npy", param_folder + "/scale4b13_branch2a_W.npy", param_folder + "/scale4b13_branch2a_b.npy"),
    bn4b13_branch2b(param_folder + "/bn4b13_branch2b_mean.npy", param_folder + "/bn4b13_branch2b_var.npy", param_folder + "/scale4b13_branch2b_W.npy", param_folder + "/scale4b13_branch2b_b.npy"),
    bn4b13_branch2c(param_folder + "/bn4b13_branch2c_mean.npy", param_folder + "/bn4b13_branch2c_var.npy", param_folder + "/scale4b13_branch2c_W.npy", param_folder + "/scale4b13_branch2c_b.npy"),
    bn4b14_branch2a(param_folder + "/bn4b14_branch2a_mean.npy", param_folder + "/bn4b14_branch2a_var.npy", param_folder + "/scale4b14_branch2a_W.npy", param_folder + "/scale4b14_branch2a_b.npy"),
    bn4b14_branch2b(param_folder + "/bn4b14_branch2b_mean.npy", param_folder + "/bn4b14_branch2b_var.npy", param_folder + "/scale4b14_branch2b_W.npy", param_folder + "/scale4b14_branch2b_b.npy"),
    bn4b14_branch2c(param_folder + "/bn4b14_branch2c_mean.npy", param_folder + "/bn4b14_branch2c_var.npy", param_folder + "/scale4b14_branch2c_W.npy", param_folder + "/scale4b14_branch2c_b.npy"),
    bn4b15_branch2a(param_folder + "/bn4b15_branch2a_mean.npy", param_folder + "/bn4b15_branch2a_var.npy", param_folder + "/scale4b15_branch2a_W.npy", param_folder + "/scale4b15_branch2a_b.npy"),
    bn4b15_branch2b(param_folder + "/bn4b15_branch2b_mean.npy", param_folder + "/bn4b15_branch2b_var.npy", param_folder + "/scale4b15_branch2b_W.npy", param_folder + "/scale4b15_branch2b_b.npy"),
    bn4b15_branch2c(param_folder + "/bn4b15_branch2c_mean.npy", param_folder + "/bn4b15_branch2c_var.npy", param_folder + "/scale4b15_branch2c_W.npy", param_folder + "/scale4b15_branch2c_b.npy"),
    bn4b16_branch2a(param_folder + "/bn4b16_branch2a_mean.npy", param_folder + "/bn4b16_branch2a_var.npy", param_folder + "/scale4b16_branch2a_W.npy", param_folder + "/scale4b16_branch2a_b.npy"),
    bn4b16_branch2b(param_folder + "/bn4b16_branch2b_mean.npy", param_folder + "/bn4b16_branch2b_var.npy", param_folder + "/scale4b16_branch2b_W.npy", param_folder + "/scale4b16_branch2b_b.npy"),
    bn4b16_branch2c(param_folder + "/bn4b16_branch2c_mean.npy", param_folder + "/bn4b16_branch2c_var.npy", param_folder + "/scale4b16_branch2c_W.npy", param_folder + "/scale4b16_branch2c_b.npy"),
    bn4b17_branch2a(param_folder + "/bn4b17_branch2a_mean.npy", param_folder + "/bn4b17_branch2a_var.npy", param_folder + "/scale4b17_branch2a_W.npy", param_folder + "/scale4b17_branch2a_b.npy"),
    bn4b17_branch2b(param_folder + "/bn4b17_branch2b_mean.npy", param_folder + "/bn4b17_branch2b_var.npy", param_folder + "/scale4b17_branch2b_W.npy", param_folder + "/scale4b17_branch2b_b.npy"),
    bn4b17_branch2c(param_folder + "/bn4b17_branch2c_mean.npy", param_folder + "/bn4b17_branch2c_var.npy", param_folder + "/scale4b17_branch2c_W.npy", param_folder + "/scale4b17_branch2c_b.npy"),
    bn4b18_branch2a(param_folder + "/bn4b18_branch2a_mean.npy", param_folder + "/bn4b18_branch2a_var.npy", param_folder + "/scale4b18_branch2a_W.npy", param_folder + "/scale4b18_branch2a_b.npy"),
    bn4b18_branch2b(param_folder + "/bn4b18_branch2b_mean.npy", param_folder + "/bn4b18_branch2b_var.npy", param_folder + "/scale4b18_branch2b_W.npy", param_folder + "/scale4b18_branch2b_b.npy"),
    bn4b18_branch2c(param_folder + "/bn4b18_branch2c_mean.npy", param_folder + "/bn4b18_branch2c_var.npy", param_folder + "/scale4b18_branch2c_W.npy", param_folder + "/scale4b18_branch2c_b.npy"),
    bn4b19_branch2a(param_folder + "/bn4b19_branch2a_mean.npy", param_folder + "/bn4b19_branch2a_var.npy", param_folder + "/scale4b19_branch2a_W.npy", param_folder + "/scale4b19_branch2a_b.npy"),
    bn4b19_branch2b(param_folder + "/bn4b19_branch2b_mean.npy", param_folder + "/bn4b19_branch2b_var.npy", param_folder + "/scale4b19_branch2b_W.npy", param_folder + "/scale4b19_branch2b_b.npy"),
    bn4b19_branch2c(param_folder + "/bn4b19_branch2c_mean.npy", param_folder + "/bn4b19_branch2c_var.npy", param_folder + "/scale4b19_branch2c_W.npy", param_folder + "/scale4b19_branch2c_b.npy"),
    bn4b20_branch2a(param_folder + "/bn4b20_branch2a_mean.npy", param_folder + "/bn4b20_branch2a_var.npy", param_folder + "/scale4b20_branch2a_W.npy", param_folder + "/scale4b20_branch2a_b.npy"),
    bn4b20_branch2b(param_folder + "/bn4b20_branch2b_mean.npy", param_folder + "/bn4b20_branch2b_var.npy", param_folder + "/scale4b20_branch2b_W.npy", param_folder + "/scale4b20_branch2b_b.npy"),
    bn4b20_branch2c(param_folder + "/bn4b20_branch2c_mean.npy", param_folder + "/bn4b20_branch2c_var.npy", param_folder + "/scale4b20_branch2c_W.npy", param_folder + "/scale4b20_branch2c_b.npy"),
    bn4b21_branch2a(param_folder + "/bn4b21_branch2a_mean.npy", param_folder + "/bn4b21_branch2a_var.npy", param_folder + "/scale4b21_branch2a_W.npy", param_folder + "/scale4b21_branch2a_b.npy"),
    bn4b21_branch2b(param_folder + "/bn4b21_branch2b_mean.npy", param_folder + "/bn4b21_branch2b_var.npy", param_folder + "/scale4b21_branch2b_W.npy", param_folder + "/scale4b21_branch2b_b.npy"),
    bn4b21_branch2c(param_folder + "/bn4b21_branch2c_mean.npy", param_folder + "/bn4b21_branch2c_var.npy", param_folder + "/scale4b21_branch2c_W.npy", param_folder + "/scale4b21_branch2c_b.npy"),
    bn4b22_branch2a(param_folder + "/bn4b22_branch2a_mean.npy", param_folder + "/bn4b22_branch2a_var.npy", param_folder + "/scale4b22_branch2a_W.npy", param_folder + "/scale4b22_branch2a_b.npy"),
    bn4b22_branch2b(param_folder + "/bn4b22_branch2b_mean.npy", param_folder + "/bn4b22_branch2b_var.npy", param_folder + "/scale4b22_branch2b_W.npy", param_folder + "/scale4b22_branch2b_b.npy"),
    bn4b22_branch2c(param_folder + "/bn4b22_branch2c_mean.npy", param_folder + "/bn4b22_branch2c_var.npy", param_folder + "/scale4b22_branch2c_W.npy", param_folder + "/scale4b22_branch2c_b.npy"),
    bn4b23_branch2a(param_folder + "/bn4b23_branch2a_mean.npy", param_folder + "/bn4b23_branch2a_var.npy", param_folder + "/scale4b23_branch2a_W.npy", param_folder + "/scale4b23_branch2a_b.npy"),
    bn4b23_branch2b(param_folder + "/bn4b23_branch2b_mean.npy", param_folder + "/bn4b23_branch2b_var.npy", param_folder + "/scale4b23_branch2b_W.npy", param_folder + "/scale4b23_branch2b_b.npy"),
    bn4b23_branch2c(param_folder + "/bn4b23_branch2c_mean.npy", param_folder + "/bn4b23_branch2c_var.npy", param_folder + "/scale4b23_branch2c_W.npy", param_folder + "/scale4b23_branch2c_b.npy"),
    bn4b24_branch2a(param_folder + "/bn4b24_branch2a_mean.npy", param_folder + "/bn4b24_branch2a_var.npy", param_folder + "/scale4b24_branch2a_W.npy", param_folder + "/scale4b24_branch2a_b.npy"),
    bn4b24_branch2b(param_folder + "/bn4b24_branch2b_mean.npy", param_folder + "/bn4b24_branch2b_var.npy", param_folder + "/scale4b24_branch2b_W.npy", param_folder + "/scale4b24_branch2b_b.npy"),
    bn4b24_branch2c(param_folder + "/bn4b24_branch2c_mean.npy", param_folder + "/bn4b24_branch2c_var.npy", param_folder + "/scale4b24_branch2c_W.npy", param_folder + "/scale4b24_branch2c_b.npy"),
    bn4b25_branch2a(param_folder + "/bn4b25_branch2a_mean.npy", param_folder + "/bn4b25_branch2a_var.npy", param_folder + "/scale4b25_branch2a_W.npy", param_folder + "/scale4b25_branch2a_b.npy"),
    bn4b25_branch2b(param_folder + "/bn4b25_branch2b_mean.npy", param_folder + "/bn4b25_branch2b_var.npy", param_folder + "/scale4b25_branch2b_W.npy", param_folder + "/scale4b25_branch2b_b.npy"),
    bn4b25_branch2c(param_folder + "/bn4b25_branch2c_mean.npy", param_folder + "/bn4b25_branch2c_var.npy", param_folder + "/scale4b25_branch2c_W.npy", param_folder + "/scale4b25_branch2c_b.npy"),
    bn4b26_branch2a(param_folder + "/bn4b26_branch2a_mean.npy", param_folder + "/bn4b26_branch2a_var.npy", param_folder + "/scale4b26_branch2a_W.npy", param_folder + "/scale4b26_branch2a_b.npy"),
    bn4b26_branch2b(param_folder + "/bn4b26_branch2b_mean.npy", param_folder + "/bn4b26_branch2b_var.npy", param_folder + "/scale4b26_branch2b_W.npy", param_folder + "/scale4b26_branch2b_b.npy"),
    bn4b26_branch2c(param_folder + "/bn4b26_branch2c_mean.npy", param_folder + "/bn4b26_branch2c_var.npy", param_folder + "/scale4b26_branch2c_W.npy", param_folder + "/scale4b26_branch2c_b.npy"),
    bn4b27_branch2a(param_folder + "/bn4b27_branch2a_mean.npy", param_folder + "/bn4b27_branch2a_var.npy", param_folder + "/scale4b27_branch2a_W.npy", param_folder + "/scale4b27_branch2a_b.npy"),
    bn4b27_branch2b(param_folder + "/bn4b27_branch2b_mean.npy", param_folder + "/bn4b27_branch2b_var.npy", param_folder + "/scale4b27_branch2b_W.npy", param_folder + "/scale4b27_branch2b_b.npy"),
    bn4b27_branch2c(param_folder + "/bn4b27_branch2c_mean.npy", param_folder + "/bn4b27_branch2c_var.npy", param_folder + "/scale4b27_branch2c_W.npy", param_folder + "/scale4b27_branch2c_b.npy"),
    bn4b28_branch2a(param_folder + "/bn4b28_branch2a_mean.npy", param_folder + "/bn4b28_branch2a_var.npy", param_folder + "/scale4b28_branch2a_W.npy", param_folder + "/scale4b28_branch2a_b.npy"),
    bn4b28_branch2b(param_folder + "/bn4b28_branch2b_mean.npy", param_folder + "/bn4b28_branch2b_var.npy", param_folder + "/scale4b28_branch2b_W.npy", param_folder + "/scale4b28_branch2b_b.npy"),
    bn4b28_branch2c(param_folder + "/bn4b28_branch2c_mean.npy", param_folder + "/bn4b28_branch2c_var.npy", param_folder + "/scale4b28_branch2c_W.npy", param_folder + "/scale4b28_branch2c_b.npy"),
    bn4b29_branch2a(param_folder + "/bn4b29_branch2a_mean.npy", param_folder + "/bn4b29_branch2a_var.npy", param_folder + "/scale4b29_branch2a_W.npy", param_folder + "/scale4b29_branch2a_b.npy"),
    bn4b29_branch2b(param_folder + "/bn4b29_branch2b_mean.npy", param_folder + "/bn4b29_branch2b_var.npy", param_folder + "/scale4b29_branch2b_W.npy", param_folder + "/scale4b29_branch2b_b.npy"),
    bn4b29_branch2c(param_folder + "/bn4b29_branch2c_mean.npy", param_folder + "/bn4b29_branch2c_var.npy", param_folder + "/scale4b29_branch2c_W.npy", param_folder + "/scale4b29_branch2c_b.npy"),
    bn4b30_branch2a(param_folder + "/bn4b30_branch2a_mean.npy", param_folder + "/bn4b30_branch2a_var.npy", param_folder + "/scale4b30_branch2a_W.npy", param_folder + "/scale4b30_branch2a_b.npy"),
    bn4b30_branch2b(param_folder + "/bn4b30_branch2b_mean.npy", param_folder + "/bn4b30_branch2b_var.npy", param_folder + "/scale4b30_branch2b_W.npy", param_folder + "/scale4b30_branch2b_b.npy"),
    bn4b30_branch2c(param_folder + "/bn4b30_branch2c_mean.npy", param_folder + "/bn4b30_branch2c_var.npy", param_folder + "/scale4b30_branch2c_W.npy", param_folder + "/scale4b30_branch2c_b.npy"),
    bn4b31_branch2a(param_folder + "/bn4b31_branch2a_mean.npy", param_folder + "/bn4b31_branch2a_var.npy", param_folder + "/scale4b31_branch2a_W.npy", param_folder + "/scale4b31_branch2a_b.npy"),
    bn4b31_branch2b(param_folder + "/bn4b31_branch2b_mean.npy", param_folder + "/bn4b31_branch2b_var.npy", param_folder + "/scale4b31_branch2b_W.npy", param_folder + "/scale4b31_branch2b_b.npy"),
    bn4b31_branch2c(param_folder + "/bn4b31_branch2c_mean.npy", param_folder + "/bn4b31_branch2c_var.npy", param_folder + "/scale4b31_branch2c_W.npy", param_folder + "/scale4b31_branch2c_b.npy"),
    bn4b32_branch2a(param_folder + "/bn4b32_branch2a_mean.npy", param_folder + "/bn4b32_branch2a_var.npy", param_folder + "/scale4b32_branch2a_W.npy", param_folder + "/scale4b32_branch2a_b.npy"),
    bn4b32_branch2b(param_folder + "/bn4b32_branch2b_mean.npy", param_folder + "/bn4b32_branch2b_var.npy", param_folder + "/scale4b32_branch2b_W.npy", param_folder + "/scale4b32_branch2b_b.npy"),
    bn4b32_branch2c(param_folder + "/bn4b32_branch2c_mean.npy", param_folder + "/bn4b32_branch2c_var.npy", param_folder + "/scale4b32_branch2c_W.npy", param_folder + "/scale4b32_branch2c_b.npy"),
    bn4b33_branch2a(param_folder + "/bn4b33_branch2a_mean.npy", param_folder + "/bn4b33_branch2a_var.npy", param_folder + "/scale4b33_branch2a_W.npy", param_folder + "/scale4b33_branch2a_b.npy"),
    bn4b33_branch2b(param_folder + "/bn4b33_branch2b_mean.npy", param_folder + "/bn4b33_branch2b_var.npy", param_folder + "/scale4b33_branch2b_W.npy", param_folder + "/scale4b33_branch2b_b.npy"),
    bn4b33_branch2c(param_folder + "/bn4b33_branch2c_mean.npy", param_folder + "/bn4b33_branch2c_var.npy", param_folder + "/scale4b33_branch2c_W.npy", param_folder + "/scale4b33_branch2c_b.npy"),
    bn4b34_branch2a(param_folder + "/bn4b34_branch2a_mean.npy", param_folder + "/bn4b34_branch2a_var.npy", param_folder + "/scale4b34_branch2a_W.npy", param_folder + "/scale4b34_branch2a_b.npy"),
    bn4b34_branch2b(param_folder + "/bn4b34_branch2b_mean.npy", param_folder + "/bn4b34_branch2b_var.npy", param_folder + "/scale4b34_branch2b_W.npy", param_folder + "/scale4b34_branch2b_b.npy"),
    bn4b34_branch2c(param_folder + "/bn4b34_branch2c_mean.npy", param_folder + "/bn4b34_branch2c_var.npy", param_folder + "/scale4b34_branch2c_W.npy", param_folder + "/scale4b34_branch2c_b.npy"),
    bn4b35_branch2a(param_folder + "/bn4b35_branch2a_mean.npy", param_folder + "/bn4b35_branch2a_var.npy", param_folder + "/scale4b35_branch2a_W.npy", param_folder + "/scale4b35_branch2a_b.npy"),
    bn4b35_branch2b(param_folder + "/bn4b35_branch2b_mean.npy", param_folder + "/bn4b35_branch2b_var.npy", param_folder + "/scale4b35_branch2b_W.npy", param_folder + "/scale4b35_branch2b_b.npy"),
    bn4b35_branch2c(param_folder + "/bn4b35_branch2c_mean.npy", param_folder + "/bn4b35_branch2c_var.npy", param_folder + "/scale4b35_branch2c_W.npy", param_folder + "/scale4b35_branch2c_b.npy"),

    bn5a_branch1(param_folder + "/bn5a_branch1_mean.npy", param_folder + "/bn5a_branch1_var.npy", param_folder + "/scale5a_branch1_W.npy", param_folder + "/scale5a_branch1_b.npy"),
    bn5a_branch2a(param_folder + "/bn5a_branch2a_mean.npy", param_folder + "/bn5a_branch2a_var.npy", param_folder + "/scale5a_branch2a_W.npy", param_folder + "/scale5a_branch2a_b.npy"),
    bn5a_branch2b(param_folder + "/bn5a_branch2b_mean.npy", param_folder + "/bn5a_branch2b_var.npy", param_folder + "/scale5a_branch2b_W.npy", param_folder + "/scale5a_branch2b_b.npy"),
    bn5a_branch2c(param_folder + "/bn5a_branch2c_mean.npy", param_folder + "/bn5a_branch2c_var.npy", param_folder + "/scale5a_branch2c_W.npy", param_folder + "/scale5a_branch2c_b.npy"),
    bn5b_branch2a(param_folder + "/bn5b_branch2a_mean.npy", param_folder + "/bn5b_branch2a_var.npy", param_folder + "/scale5b_branch2a_W.npy", param_folder + "/scale5b_branch2a_b.npy"),
    bn5b_branch2b(param_folder + "/bn5b_branch2b_mean.npy", param_folder + "/bn5b_branch2b_var.npy", param_folder + "/scale5b_branch2b_W.npy", param_folder + "/scale5b_branch2b_b.npy"),
    bn5b_branch2c(param_folder + "/bn5b_branch2c_mean.npy", param_folder + "/bn5b_branch2c_var.npy", param_folder + "/scale5b_branch2c_W.npy", param_folder + "/scale5b_branch2c_b.npy"),
    bn5c_branch2a(param_folder + "/bn5c_branch2a_mean.npy", param_folder + "/bn5c_branch2a_var.npy", param_folder + "/scale5c_branch2a_W.npy", param_folder + "/scale5c_branch2a_b.npy"),
    bn5c_branch2b(param_folder + "/bn5c_branch2b_mean.npy", param_folder + "/bn5c_branch2b_var.npy", param_folder + "/scale5c_branch2b_W.npy", param_folder + "/scale5c_branch2b_b.npy"),
    bn5c_branch2c(param_folder + "/bn5c_branch2c_mean.npy", param_folder + "/bn5c_branch2c_var.npy", param_folder + "/scale5c_branch2c_W.npy", param_folder + "/scale5c_branch2c_b.npy"),


    // Fully connected layer
    fc1000(param_folder + "/fc1000_W.npy", param_folder + "/fc1000_b.npy",
	       param_folder + "/decomposition/fc1000_W/basis_6/M.npy",
		   param_folder + "/decomposition/fc1000_W/basis_6/c.npy")
{}